### ISSUE TITLE
Judge, lest not ye be judged...

### ISSUE THREAD

**Issue by justingoldberg** [milahu/hate-maintainers-censored#1]
start your own hate free distro with @micahflee 

https://micahflee.com/

https://web.archive.org/web/20230222112654/https://discourse.nixos.org/t/where-can-i-find-the-context-when-a-user-is-banned/25674

**Comment by milahu** [comment]
> Judge, lest not ye be judged

yeah, i appreciate all kinds of feedback, and i would block people only for actual spam or abuse, similar to gab.com

> start your own hate free distro

what? "hate free" is not my style. and nixos linux is good enough, so no reason to reinvent that wheel
